/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ownable from "./ownable";
export type { ownable };
export type { IERC173 } from "./IERC173";
export type { IERC173Internal } from "./IERC173Internal";
