/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from "./base";
export * as extensions from "./extensions";
export { ISemaphore__factory } from "./ISemaphore__factory";
export { ISemaphoreGroups__factory } from "./ISemaphoreGroups__factory";
export { ISemaphoreInternal__factory } from "./ISemaphoreInternal__factory";
export { Semaphore__factory } from "./Semaphore__factory";
export { SemaphoreInternal__factory } from "./SemaphoreInternal__factory";
