/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISemaphoreInternal,
  ISemaphoreInternalInterface,
} from "../../../contracts/semaphore/ISemaphoreInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "groupId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "signal",
        type: "bytes32",
      },
    ],
    name: "ProofVerified",
    type: "event",
  },
];

export class ISemaphoreInternal__factory {
  static readonly abi = _abi;
  static createInterface(): ISemaphoreInternalInterface {
    return new utils.Interface(_abi) as ISemaphoreInternalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISemaphoreInternal {
    return new Contract(address, _abi, signerOrProvider) as ISemaphoreInternal;
  }
}
