/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWalletFactoryDiamond,
  IWalletFactoryDiamondInterface,
} from "../../../contracts/diamond/IWalletFactoryDiamond";

const _abi = [
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWalletFactoryDiamond__factory {
  static readonly abi = _abi;
  static createInterface(): IWalletFactoryDiamondInterface {
    return new utils.Interface(_abi) as IWalletFactoryDiamondInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWalletFactoryDiamond {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IWalletFactoryDiamond;
  }
}
