/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ERC721ServiceInternal,
  ERC721ServiceInternalInterface,
} from "../../../../contracts/token/ERC721/ERC721ServiceInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "ERC721TokenRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "ERC721TokenTracked",
    type: "event",
  },
];

export class ERC721ServiceInternal__factory {
  static readonly abi = _abi;
  static createInterface(): ERC721ServiceInternalInterface {
    return new utils.Interface(_abi) as ERC721ServiceInternalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC721ServiceInternal {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC721ServiceInternal;
  }
}
