/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as semaphoreCoreBase from "./SemaphoreCoreBase";
export * as semaphoreGroupsBase from "./SemaphoreGroupsBase";
