/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISemaphoreCoreBase } from "./ISemaphoreCoreBase";
export type { ISemaphoreCoreBaseInternal } from "./ISemaphoreCoreBaseInternal";
export type { SemaphoreCoreBase } from "./SemaphoreCoreBase";
export type { SemaphoreCoreBaseInternal } from "./SemaphoreCoreBaseInternal";
export type { SemaphoreCoreBaseMock } from "./SemaphoreCoreBaseMock";
