/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiamondWritable__factory } from "./DiamondWritable__factory";
export { IDiamondWritable__factory } from "./IDiamondWritable__factory";
