/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISemaphoreCoreBaseInternal,
  ISemaphoreCoreBaseInternalInterface,
} from "../../../../../contracts/semaphore/base/SemaphoreCoreBase/ISemaphoreCoreBaseInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "nullifierHash",
        type: "uint256",
      },
    ],
    name: "NullifierHashAdded",
    type: "event",
  },
];

export class ISemaphoreCoreBaseInternal__factory {
  static readonly abi = _abi;
  static createInterface(): ISemaphoreCoreBaseInternalInterface {
    return new utils.Interface(_abi) as ISemaphoreCoreBaseInternalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISemaphoreCoreBaseInternal {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISemaphoreCoreBaseInternal;
  }
}
