/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISemaphoreCoreBase,
  ISemaphoreCoreBaseInterface,
} from "../../../../../contracts/semaphore/base/SemaphoreCoreBase/ISemaphoreCoreBase";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "nullifierHash",
        type: "uint256",
      },
    ],
    name: "NullifierHashAdded",
    type: "event",
  },
];

export class ISemaphoreCoreBase__factory {
  static readonly abi = _abi;
  static createInterface(): ISemaphoreCoreBaseInterface {
    return new utils.Interface(_abi) as ISemaphoreCoreBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISemaphoreCoreBase {
    return new Contract(address, _abi, signerOrProvider) as ISemaphoreCoreBase;
  }
}
