/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SemaphoreCoreBase,
  SemaphoreCoreBaseInterface,
} from "../../../../../contracts/semaphore/base/SemaphoreCoreBase/SemaphoreCoreBase";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "nullifierHash",
        type: "uint256",
      },
    ],
    name: "NullifierHashAdded",
    type: "event",
  },
];

export class SemaphoreCoreBase__factory {
  static readonly abi = _abi;
  static createInterface(): SemaphoreCoreBaseInterface {
    return new utils.Interface(_abi) as SemaphoreCoreBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SemaphoreCoreBase {
    return new Contract(address, _abi, signerOrProvider) as SemaphoreCoreBase;
  }
}
