/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SemaphoreVotingInternal,
  SemaphoreVotingInternalInterface,
} from "../../../../../contracts/semaphore/extensions/SemaphoreVoting/SemaphoreVotingInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "nullifierHash",
        type: "uint256",
      },
    ],
    name: "NullifierHashAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "pollId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "coordinator",
        type: "address",
      },
    ],
    name: "PollCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "pollId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "coordinator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "decryptionKey",
        type: "uint256",
      },
    ],
    name: "PollEnded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "pollId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "coordinator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "encryptionKey",
        type: "uint256",
      },
    ],
    name: "PollStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "groupId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "signal",
        type: "bytes32",
      },
    ],
    name: "ProofVerified",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "pollId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "vote",
        type: "bytes32",
      },
    ],
    name: "VoteAdded",
    type: "event",
  },
];

export class SemaphoreVotingInternal__factory {
  static readonly abi = _abi;
  static createInterface(): SemaphoreVotingInternalInterface {
    return new utils.Interface(_abi) as SemaphoreVotingInternalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SemaphoreVotingInternal {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SemaphoreVotingInternal;
  }
}
