/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISemaphoreGroupsBase__factory } from "./ISemaphoreGroupsBase__factory";
export { ISemaphoreGroupsInternal__factory } from "./ISemaphoreGroupsInternal__factory";
export { SemaphoreGroupsBase__factory } from "./SemaphoreGroupsBase__factory";
export { SemaphoreGroupsBaseInternal__factory } from "./SemaphoreGroupsBaseInternal__factory";
export { SemaphoreGroupsBaseMock__factory } from "./SemaphoreGroupsBaseMock__factory";
